name: spotegal
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2 
  curved_navigation_bar: any
  flutter_staggered_grid_view: ^0.3.0
  flutter_swiper: any
  shared_preferences: any
  http: any
  fluttertoast: any
  carousel_pro: any
  carousel_slider: any

  google_maps_flutter: any
  json_serializable: any
  font_awesome_flutter: any
  image_picker: ^0.6.7+1
  firebase_dynamic_links: ^0.5.1
  share: ^0.6.4+3
  # image_picker: ^0.6.2+3


  splashscreen: any

  flutter_launcher_icons: any

  pedantic: any
  build_runner: 
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_messaging: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/img/
    - assets/img/slide/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: FontJudul
      fonts:
        - asset: fonts/font_judul.ttf

    - family: FontBiasa
      fonts:
        - asset: fonts/font_biasa.ttf

    - family: FontFavorit
      fonts:
        - asset: fonts/font_favorit.ttf
        - asset: fonts/font_favorit_bold.ttf
    - family: FontFavoritBold
      fonts:
        - asset: fonts/font_favorit_bold.ttf
        
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/ic_spotegal.png"

  #flutter pub pub run flutter_launcher_icons:main

